[Unit]
ConditionPathExists=/run/pilink-control/adapter.env

[Service]
EnvironmentFile=/run/pilink-control/adapter.env
ExecStartPre=/usr/local/libexec/pilink-service-control validate --adapter ${PILINK_ADAPTER} --address ${PILINK_ADAPTER_ADDRESS}
ExecStart=
ExecStart=/usr/local/libexec/pilink-network service --adapter ${PILINK_ADAPTER} --mode internet
