[Unit]
ConditionPathExists=/run/rpi-ble-tunnel-control/adapter.env

[Service]
EnvironmentFile=/run/rpi-ble-tunnel-control/adapter.env
ExecStartPre=/usr/local/libexec/rpi-ble-tunnel-service-control validate --adapter ${RPI_BLE_TUNNEL_ADAPTER} --address ${RPI_BLE_TUNNEL_ADAPTER_ADDRESS}
ExecStart=
ExecStart=/usr/local/libexec/rpi-ble-tunnel-network service --adapter ${RPI_BLE_TUNNEL_ADAPTER} --mode internet
